version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:eu-central-1:329599647651:task-definition/todo-app-task:2"
        LoadBalancerInfo:
          ContainerName: "todo-app-container"
          ContainerPort: 8080
        PlatformVersion: "LATEST"