package com.mascot.todo_app.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "todo-app")
public class Task {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String title;

    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateConverter.class)
    private LocalDate dueDate;

    @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    private Status status;


    // Custom converter for LocalDate
    public static class LocalDateConverter implements DynamoDBTypeConverter<String, LocalDate> {
        private static final DateTimeFormatter FORMATTER = DateTimeFormatter.ISO_LOCAL_DATE;

        @Override
        public String convert(LocalDate localDate) {
            return localDate.format(FORMATTER);
        }

        @Override
        public LocalDate unconvert(String s) {
            return LocalDate.parse(s, FORMATTER);
        }

    }
}
