name: Deploy DynamoDB with SAM

on:
  push:
    branches:
      - main
    paths:
      - 'sam-template.yaml'
      - '.github/workflows/deploy-sam.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aws-sam-cli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: SAM build
        run: sam build --template-file sam-template.yaml

      - name: SAM deploy
        run: |
          sam deploy \
            --stack-name todo-app-dynamodb \
            --template-file sam-template.yaml \
            --capabilities CAPABILITY_IAM \
            --no-fail-on-empty-changeset